# Generated by Django 5.2.6 on 2025-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorites",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="rate",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
