# Generated by Django 4.2.6 on 2025-11-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="favorites",
        ),
        migrations.AddField(
            model_name="post",
            name="favorites",
            field=models.BooleanField(default=False),
        ),
    ]
