services:
  web:
    build: .
    env_file: .env
    depends_on: [db]
    command: ["/start.sh"]
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - "8001:8000"   # اضافه شد: هاست:کانتینر
    restart: unless-stopped

  db:
    image: postgres:16

volumes:
  pgdata:
  static:
  media:
  
