services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    command: ["/start.sh"]          # ← Prod: gunicorn
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: strong_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static
      - media:/media
    restart: unless-stopped

volumes:
  pgdata:
  static:
  media:
