# Generated by Django 5.2.6 on 2025-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmapsection",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
