# Generated by Django 5.2.6 on 2025-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=600)),
                ("goal", models.CharField(max_length=250)),
                ("strategy", models.CharField(max_length=250)),
                ("roal", models.CharField(max_length=250)),
                ("personality", models.CharField(max_length=250)),
                ("age", models.PositiveIntegerField(default=0)),
                ("sex", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
