# Generated by Django 4.2.6 on 2025-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/character_avatars/"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/character_images/"
            ),
        ),
    ]
