# Generated by Django 4.2.6 on 2025-11-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_character_avatar_character_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="slogan",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="character",
            name="symbols",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="character",
            name="weekness",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="character",
            name="strategy",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
