# Generated by Django 5.2.6 on 2025-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(upload_to="assets/team_photos/"),
        ),
    ]
