# Generated by Django 4.2.6 on 2025-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_teammember_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(upload_to="team_photos/"),
        ),
    ]
