# Generated by Django 4.2.6 on 2025-11-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_teammember_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="teammember",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
